name: build-flow-os
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Salix Image
        run: |
          cat <<EOF > Containerfile
          FROM quay.io/fedora-ostree-desktops/kinoite:41
          RUN curl -s https://pkg.surfacelinux.com/fedora/linux-surface.repo -o /etc/yum.repos.d/linux-surface.repo
          RUN rpm-ostree install kernel-surface surface-control iptsd libwacom-surface && rpm-ostree cleanup -a
          RUN rpm-ostree override remove kernel kernel-core kernel-modules kernel-modules-extra --install kernel-surface
          EOF
          buildah bud -t flow-os:latest .

      - name: Push to GitHub Packages
        run: |
          echo "${{ github.token }}" | buildah login ghcr.io -u ${{ github.actor }} --password-stdin
          buildah push flow-os:latest docker://ghcr.io/${{ github.repository_owner }}/salix:latest
